package proyecto.enums;

public enum TipoIndicadorEnum {
    CANTIDAD_RESIDUOS_GENERADOS_KG_MES,
    CANTIDAD_RESIDUOS_GENERADOS_KG_ANIO,
    CANTIDAD_RESIDUOS_POR_UNIDAD_PRODUCCION,
    CONSUMO_TOTAL_AGUA_M3_MES,
    CONSUMO_TOTAL_AGUA_M3_ANIO,
    CONSUMO_AGUA_POZO_CANTIDAD,
    CAUDAL_VUELCO_EFLUENTES_M3_MES,
    CAUDAL_VUELCO_EFLUENTES_M3_ANIO,
    PORCENTAJE_DESVIOS_VUELCO,
    CONSUMO_AGUA_POR_UNIDAD_PRODUCCION,
    CONSUMO_TOTAL_ENERGIA_ELECTRICA_KWH_MES,
    CONSUMO_TOTAL_ENERGIA_ELECTRICA_KWH_ANIO,
    CONSUMO_ENERGETICO_POR_UNIDAD_PRODUCCION,
    VOLUMEN_BIOCOMBUSTIBLE_GENERADO,
    CONSUMO_TOTAL_GAS_M3,
    CONSUMO_ENERGIA_TERMICA_POR_PRODUCTO,
    CONSUMO_COMBUSTIBLES_LITROS,
    CONSUMO_COMBUSTIBLES_LIQUIDOS_POR_PRODUCCION,
    NUMERO_ACCIDENTES_AMBIENTALES,
    PORCENTAJE_PRESUPUESTO_TECNOLOGIAS_BAJAS_EMISIONES
}